// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  rich_text: dynamic(() => import("./RichText")),
  feature: dynamic(() => import("./Feature")),
  hero_heading: dynamic(() => import("./Hero")),
};
