// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  big_image: dynamic(() => import("./BigImage")),
  home_hero: dynamic(() => import("./HomeHero")),
};
